services:
  postgres:
    image: postgres:17
    container_name: devtasks-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devtasks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: devtasks-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@devtasks.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  pgdata:



